### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by guavuavcycayfayqvqu** [emlearn/emlearn-micropython#10]
After a long search i goy this. Now i can use in esp32 s3❤️

**Comment by jonnor** [comment]
Hi @guavuavcycayfayqvqu - glad to hear someone finds this useful! What kind of projects / applications are you most interested in?

**Comment by guavuavcycayfayqvqu** [comment]
> Hi @guavuavcycayfayqvqu - glad to hear someone finds this useful! What kind of projects / applications are you most interested in?

Maybe i will train it and use for something like alexa/ face recognition and there are vast possibly 😊.

**Comment by guavuavcycayfayqvqu** [comment]
And maybe we can make a real micro-mouse which use ai not algorithm 😶‍🌫️

**Comment by jonnor** [comment]
I am hoping that the CNN support using TinyMaix that I just added will make speech command recognition and basic computer vision task possible :)

Robotics is also a fun usage of TinyML. Though I have not see so much of it this far?

**Comment by guavuavcycayfayqvqu** [comment]
Nice. I appreciate that 😊.

**Comment by jonnor** [comment]
Closing since it is not an issue :) I have enabled discussion board now for emlearn project. So when you start making something, feel free to open a thread there!
